var masjidList1 = [
  {
    MosqueID: 5,
    MosqueName: "Masjid Abdul Aleem Siddique",
    ZoneID: 4,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 6,
    MosqueName: "Masjid Al Abdul Razak",
    ZoneID: 5,
    ZoneName: "Zone 1 (Level 1)",
  },
];

var masjidList = [
  {
    MosqueID: 5,
    MosqueName: "Masjid Abdul Aleem Siddique",
    ZoneID: 4,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 6,
    MosqueName: "Masjid Al Abdul Razak",
    ZoneID: 5,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 7,
    MosqueName: "Masjid Al-Ansar",
    ZoneID: 6,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 8,
    MosqueName: "Masjid Al-Islah",
    ZoneID: 9,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 9,
    MosqueName: "Masjid Al-Istighfar",
    ZoneID: 13,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 10,
    MosqueName: "Masjid Alkaff Kampung Melayu",
    ZoneID: 17,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 11,
    MosqueName: "Masjid Al-Mawaddah",
    ZoneID: 20,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 12,
    MosqueName: "Masjid Al-Taqua",
    ZoneID: 23,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 13,
    MosqueName: "Masjid Darul Aman",
    ZoneID: 24,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 14,
    MosqueName: "Masjid Darul Ghufran",
    ZoneID: 26,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 15,
    MosqueName: "Masjid Haji Mohd Salleh (Geylang)",
    ZoneID: 31,
    ZoneName: "Zone 1 (Level 2)",
  },
  {
    MosqueID: 16,
    MosqueName: "Masjid Kampung Siglap",
    ZoneID: 32,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 17,
    MosqueName: "Masjid Kassim",
    ZoneID: 34,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 18,
    MosqueName: "Masjid Khadijah",
    ZoneID: 35,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 19,
    MosqueName: "Masjid Khalid",
    ZoneID: 36,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 20,
    MosqueName: "Masjid Mydin",
    ZoneID: 37,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 21,
    MosqueName: "Masjid Sallim Mattar",
    ZoneID: 38,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 22,
    MosqueName: "Masjid Wak Tanjong",
    ZoneID: 39,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 23,
    MosqueName: "Masjid Abdul Hamid (Kg Pasiran)",
    ZoneID: 40,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 24,
    MosqueName: "Masjid Ahmad Ibrahim",
    ZoneID: 41,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 25,
    MosqueName: "Masjid Al-Istiqamah",
    ZoneID: 42,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 26,
    MosqueName: "Masjid Alkaff (Upper Serangoon)",
    ZoneID: 44,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 27,
    MosqueName: "Masjid Al-Muttaqin",
    ZoneID: 45,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 28,
    MosqueName: "Masjid An-Nahdhah",
    ZoneID: 48,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 29,
    MosqueName: "Masjid An-Nur ",
    ZoneID: 51,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 30,
    MosqueName: "Masjid Assyafaah",
    ZoneID: 54,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 31,
    MosqueName: "Masjid Darul Makmur",
    ZoneID: 58,
    ZoneName: "Zone 1 (Level 2)",
  },
  {
    MosqueID: 32,
    MosqueName: "Masjid En-Naeem",
    ZoneID: 61,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 33,
    MosqueName: "Masjid Haji Yusoff",
    ZoneID: 63,
    ZoneName: "Zone 1 (Level 2)",
  },
  {
    MosqueID: 34,
    MosqueName: "Masjid Hajjah Rahimabi Kebun Limau",
    ZoneID: 65,
    ZoneName: "Zone 1 (Level 1A)",
  },
  {
    MosqueID: 35,
    MosqueName: "Masjid Muhajirin",
    ZoneID: 67,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 36,
    MosqueName: "Masjid Omar Salmah",
    ZoneID: 69,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 37,
    MosqueName: "Masjid Petempatan Melayu Sembawang",
    ZoneID: 70,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 38,
    MosqueName: "Masjid Yusof Ishak",
    ZoneID: 71,
    ZoneName: "Zone 1 (Level 2)",
  },
  {
    MosqueID: 40,
    MosqueName: "Masjid Al-Abrar",
    ZoneID: 75,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 41,
    MosqueName: "Masjid Al-Amin",
    ZoneID: 76,
    ZoneName: "Zone 1 (Level 2)",
  },
  {
    MosqueID: 42,
    MosqueName: "Masjid Al-Falah",
    ZoneID: 79,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 43,
    MosqueName: "Masjid Angullia",
    ZoneID: 143,
    ZoneName: "Zone 1 (Level 2)",
  },
  {
    MosqueID: 47,
    MosqueName: "Masjid Haji Muhammad Salleh (Palmer)",
    ZoneID: 87,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 48,
    MosqueName: "Masjid Hajjah Fatimah",
    ZoneID: 88,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 49,
    MosqueName: "Masjid Jamae (Chulia)",
    ZoneID: 89,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 50,
    MosqueName: "Masjid Jamek Queenstown",
    ZoneID: 90,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 51,
    MosqueName: "Masjid Jamiyah Ar-Rabitah",
    ZoneID: 91,
    ZoneName: "Zone 1 (Level 2)",
  },
  {
    MosqueID: 52,
    MosqueName: "Masjid Kampong Delta ",
    ZoneID: 93,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 53,
    MosqueName: "Masjid Malabar",
    ZoneID: 94,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 54,
    MosqueName: "Masjid Moulana Mohd Ali",
    ZoneID: 96,
    ZoneName: "Zone 1 (Basement)",
  },
  {
    MosqueID: 55,
    MosqueName: "Masjid Mujahidin",
    ZoneID: 97,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 56,
    MosqueName: "Masjid Omar Kampong Melaka",
    ZoneID: 101,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 57,
    MosqueName: "Masjid Sultan",
    ZoneID: 102,
    ZoneName: "Zone 1 (Level 1 - Front)",
  },
  {
    MosqueID: 58,
    MosqueName: "Masjid Tasek Utara",
    ZoneID: 105,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 59,
    MosqueName: "Masjid Ahmad",
    ZoneID: 106,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 60,
    MosqueName: "Masjid Al-Firdaus",
    ZoneID: 107,
    ZoneName: "Zone 1 (MPH Level 1)",
  },
  {
    MosqueID: 61,
    MosqueName: "Masjid Al-Huda",
    ZoneID: 108,
    ZoneName: "Zone 1 (MPH Level 1)",
  },
  {
    MosqueID: 62,
    MosqueName: "Masjid Al-Iman",
    ZoneID: 109,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 63,
    MosqueName: "Masjid Al-Khair",
    ZoneID: 114,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 64,
    MosqueName: "Masjid Al-Mukminin",
    ZoneID: 117,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 65,
    MosqueName: "Masjid Ar-Raudhah",
    ZoneID: 121,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 66,
    MosqueName: "Masjid Assyakirin",
    ZoneID: 124,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 67,
    MosqueName: "Masjid Darussalam",
    ZoneID: 129,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 68,
    MosqueName: "Masjid Hang Jebat",
    ZoneID: 131,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 69,
    MosqueName: "Masjid Hasanah",
    ZoneID: 132,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 70,
    MosqueName: "Masjid Hussein Sulaiman",
    ZoneID: 135,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 71,
    MosqueName: "Masjid Maarof",
    ZoneID: 136,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 73,
    MosqueName: "Masjid Pusara Aman",
    ZoneID: 140,
    ZoneName: "Zone 1 (Level 1)",
  },
  {
    MosqueID: 74,
    MosqueName: "Masjid Tentera Di Raja",
    ZoneID: 141,
    ZoneName: "Zone 1 (Level 1)",
  },
];
